remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
title: Probato
description: Framework for software testing automation at the functional software level
google_analytics: G-XZR907P520
theme: jekyll-theme-architect